const abi = [
  {
    type: "event",
    name: "BountyCreated",
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "string", name: "title", type: "string" },
      { indexed: false, internalType: "uint256", name: "reward", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "commitDeadline", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "revealDeadline", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "CommitmentSubmitted",
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "entryIndex", type: "uint256" },
      { indexed: true, internalType: "address", name: "participant", type: "address" },
      { indexed: false, internalType: "bytes32", name: "commitment", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "AnswerRevealed",
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "entryIndex", type: "uint256" },
      { indexed: true, internalType: "address", name: "participant", type: "address" },
    ],
  },
  {
    type: "event",
    name: "AllAnswersJudged",
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: false, internalType: "bytes", name: "aiReview", type: "bytes" },
    ],
  },
  {
    type: "event",
    name: "WinnerFinalized",
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "bountyId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "winnerIndex", type: "uint256" },
      { indexed: true, internalType: "address", name: "winner", type: "address" },
      { indexed: false, internalType: "uint256", name: "reward", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "createBounty",
    stateMutability: "payable",
    inputs: [
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "rubric", type: "string" },
      { internalType: "uint256", name: "commitDeadline", type: "uint256" },
      { internalType: "uint256", name: "revealDeadline", type: "uint256" },
    ],
    outputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
  },
  {
    type: "function",
    name: "submitCommitment",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "bytes32", name: "commitment", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "revealAnswer",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "string", name: "answer", type: "string" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "judgeAll",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "bytes", name: "llmInput", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "finalizeWinner",
    stateMutability: "nonpayable",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "uint256", name: "winnerIndex", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "refundIfNoReveals",
    stateMutability: "nonpayable",
    inputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getBounty",
    stateMutability: "view",
    inputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
    outputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "rubric", type: "string" },
      { internalType: "uint256", name: "reward", type: "uint256" },
      { internalType: "uint256", name: "commitDeadline", type: "uint256" },
      { internalType: "uint256", name: "revealDeadline", type: "uint256" },
      { internalType: "bool", name: "judged", type: "bool" },
      { internalType: "bool", name: "finalized", type: "bool" },
      { internalType: "uint256", name: "entryCountValue", type: "uint256" },
      { internalType: "uint256", name: "revealedCount", type: "uint256" },
      { internalType: "uint256", name: "winnerIndex", type: "uint256" },
      { internalType: "bytes", name: "aiReview", type: "bytes" },
    ],
  },
  {
    type: "function",
    name: "getEntry",
    stateMutability: "view",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
    outputs: [
      { internalType: "address", name: "participant", type: "address" },
      { internalType: "bytes32", name: "commitment", type: "bytes32" },
      { internalType: "bool", name: "revealed", type: "bool" },
      { internalType: "string", name: "answer", type: "string" },
    ],
  },
  {
    type: "function",
    name: "getEntryIndex",
    stateMutability: "view",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "address", name: "participant", type: "address" },
    ],
    outputs: [
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "uint256", name: "index", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "entryCount",
    stateMutability: "view",
    inputs: [{ internalType: "uint256", name: "bountyId", type: "uint256" }],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "computeCommitment",
    stateMutability: "pure",
    inputs: [
      { internalType: "uint256", name: "bountyId", type: "uint256" },
      { internalType: "string", name: "answer", type: "string" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "address", name: "participant", type: "address" },
    ],
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "nextBountyId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
  },
] as const;

export default abi;